### PR TITLE
issue #48 Minor fixes

### LINKED ISSUE #48: Minor fixes
. fix import of containers from generated components
. add export string at the beginning of each container export statement in custom/containers/index.js

### PR DESCRIPTION
**Pull request by PabloAlice**
Fix #48

### CODE REVIEW

File: examples/test-expected/generate/custom/containers/index.js [hunk 1]
```diff
@@ -1,7 +1,5 @@
 import ReduxUnicorn from './ReduxUnicorn';
 import Unicorn from './Unicorn';
 
-export default {
-  ReduxUnicorn,
-  Unicorn,
-};
\ No newline at end of file
+export { ReduxUnicorn }
```
Comment (beogip) [inline examples/test-expected/generate/custom/containers/index.js]: can we use this syntax? 
`export { ReduxUnicorn, Unicorn }`

Comment (PabloAlice) [inline examples/test-expected/generate/custom/containers/index.js]: yes, sure, i used same syntax but with export default and that threw me error, because of that i wrote it by that way. I already test it with your syntax and it works!
